import 'package:ftc_stocks/Constants/app_strings.dart';

Map<String, String> enIN = <String, String>{
  AppStrings.login: "Login",
  AppStrings.phoneNumber: "Phone Number",
  AppStrings.enterPhoneNumber: "Enter phone number",
  AppStrings.pleaseEnterPhoneNumber: "Please enter phone number.",
  AppStrings.pleaseEnterValidPhoneNumber: "Please enter valid phone number.",
  AppStrings.password: "Password",
  AppStrings.enterPassword: "Enter password",
  AppStrings.pleaseEnterPassword: "Please enter password.",
  AppStrings.temporaryServiceIsNotAvailable: "Temporary service is not available.",
  AppStrings.fileIsSavedToDownloadFolder: "File is saved to download folder.",
  AppStrings.next: "Next",
  AppStrings.hello: "Hello 👋,",
  AppStrings.createOrder: "Create Order",
  AppStrings.settings: "Settings",
  AppStrings.changeLanguage: "Change Language",
  AppStrings.english: "English",
  AppStrings.gujarati: "ગુજરાતી",
  AppStrings.addStock: "Add Stock",
  AppStrings.availableStock: "Available Stock",
  AppStrings.pendingOrders: "Pending Orders",
  AppStrings.challan: "Challan",
  AppStrings.category: "Category",
  AppStrings.selectCategory: "Select Category",
  AppStrings.noDataFound: "No data found",
  AppStrings.handle: "Handle",
  AppStrings.mainDoor: "Main Door",
  AppStrings.dabbi: "Dabbi",
  AppStrings.pleaseSelectCategory: "Please select category.",
  AppStrings.add: "Add",
  AppStrings.product: "Product",
  AppStrings.selectProduct: "Select Product",
  AppStrings.pleaseSelectProduct: "Please select product.",
  AppStrings.enterProductName: "Enter Product Name",
  AppStrings.size: "Size",
  AppStrings.selectSize: "Select Size",
  AppStrings.select: "Select",
  AppStrings.searchSize: "Search size",
  AppStrings.three: '3',
  AppStrings.four: '4',
  AppStrings.six: '6',
  AppStrings.eight: '8',
  AppStrings.ten: '10',
  AppStrings.twelve: '12',
};
