import 'package:ftc_stocks/Constants/app_strings.dart';

Map<String, String> enIN = <String, String>{
  AppStrings.login: "Login",
  AppStrings.phoneNumber: "Phone Number",
  AppStrings.enterPhoneNumber: "Enter phone number",
  AppStrings.pleaseEnterPhoneNumber: "Please enter phone number.",
  AppStrings.pleaseEnterValidPhoneNumber: "Please enter valid phone number.",
  AppStrings.password: "Password",
  AppStrings.enterPassword: "Enter password",
  AppStrings.pleaseEnterPassword: "Please enter password.",
  AppStrings.temporaryServiceIsNotAvailable: "Temporary service is not available.",
  AppStrings.fileIsSavedToDownloadFolder: "File is saved to download folder.",
  AppStrings.next: "Next",
  AppStrings.hello: "Hello 👋,",
  AppStrings.createOrder: "Create Order",
  AppStrings.settings: "Settings",
  AppStrings.changeLanguage: "Change Language",
  AppStrings.english: "English",
  AppStrings.gujarati: "ગુજરાતી",
  AppStrings.addStock: "Add Stock",
  AppStrings.availableStock: "Available Stock",
  AppStrings.pendingOrders: "Pending Orders",
  AppStrings.challan: "Challan",
};
