import 'package:ftc_stocks/Constants/app_strings.dart';

Map<String, String> guIN = <String, String>{
  AppStrings.login: "પ્રવેશ કરો",
  AppStrings.phoneNumber: "ફોન નંબર",
  AppStrings.enterPhoneNumber: "ફોન નંબર દાખલ કરો",
  AppStrings.pleaseEnterPhoneNumber: "કૃપા કરીને ફોન નંબર દાખલ કરો.",
  AppStrings.pleaseEnterValidPhoneNumber: "કૃપા કરીને માન્ય ફોન નંબર દાખલ કરો.",
  AppStrings.password: "પાસવર્ડ",
  AppStrings.enterPassword: "પાસવર્ડ દાખલ કરો",
  AppStrings.pleaseEnterPassword: "કૃપા કરીને પાસવર્ડ દાખલ કરો.",
  AppStrings.temporaryServiceIsNotAvailable: "હાલમાં સેવા ઉપલબ્ધ નથી.",
  AppStrings.fileIsSavedToDownloadFolder: "ફાઇલ ડાઉનલોડ ફોલ્ડરમાં સાચવવામાં આવે છે.",
  AppStrings.next: "આગળ",
  AppStrings.hello: "નમસ્તે 🙏,",
  AppStrings.createOrder: "ઓર્ડર ઉમેરો",
  AppStrings.settings: "સેટિંગ્સ",
  AppStrings.changeLanguage: "ભાષા બદલો",
  AppStrings.english: "English",
  AppStrings.gujarati: "ગુજરાતી",
  AppStrings.addStock: "સ્ટોક ઉમેરો",
  AppStrings.availableStock: "ઉપલબ્ધ સ્ટોક",
  AppStrings.pendingOrders: "બાકી ઓર્ડર",
  AppStrings.challan: "ચલણ",
};
