// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBL8T_Q_7xLijb26MVWQRyVAG6rwO2A1a0',
    appId: '1:1069283885682:web:c40cefe64e87b38fadb8eb',
    messagingSenderId: '1069283885682',
    projectId: 'ftc-stocks',
    authDomain: 'ftc-stocks.firebaseapp.com',
    storageBucket: 'ftc-stocks.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAi6BKbWHxlb2yuFL92C3H_8woCvsUhC1w',
    appId: '1:1069283885682:android:a8c603ffa13f29a2adb8eb',
    messagingSenderId: '1069283885682',
    projectId: 'ftc-stocks',
    storageBucket: 'ftc-stocks.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4AC_kE9dHnx8X1GtX26u7Lmhjnc1tq0Y',
    appId: '1:1069283885682:ios:d5c21df86cfa6a59adb8eb',
    messagingSenderId: '1069283885682',
    projectId: 'ftc-stocks',
    storageBucket: 'ftc-stocks.firebasestorage.app',
    iosBundleId: 'com.stocks.ftc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4AC_kE9dHnx8X1GtX26u7Lmhjnc1tq0Y',
    appId: '1:1069283885682:ios:d5c21df86cfa6a59adb8eb',
    messagingSenderId: '1069283885682',
    projectId: 'ftc-stocks',
    storageBucket: 'ftc-stocks.firebasestorage.app',
    iosBundleId: 'com.stocks.ftc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBL8T_Q_7xLijb26MVWQRyVAG6rwO2A1a0',
    appId: '1:1069283885682:web:e963fa8115fa6797adb8eb',
    messagingSenderId: '1069283885682',
    projectId: 'ftc-stocks',
    authDomain: 'ftc-stocks.firebaseapp.com',
    storageBucket: 'ftc-stocks.firebasestorage.app',
  );
}
